name: Deploy to Google Run

on: 

  push: 
    branches: [ main ]

  pull_request: 
    branches: [ main ]

env: 
  PROJECT_ID: ${{ secrets.catboostml-466504 }}
  SERVICE_NAME: catboost-api
  REGION: asia-northeast3

jobs: 

  test: 
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3

    - name: Set up Python
      uses: action/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r catboost_ml/requirements/requirements.txt
        pip install -r catboost_ml/requirements/test_requirements.txt
        pip install .

    - name: Run tests 
      run: | 
        python -m pytest tests/ -v 

  deploy: 
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps: 
    - uses: action/checkout@v3 

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker
    
    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
      
    - name: Push Docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 10
